# Generated by Django 5.2.7 on 2026-02-21 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('morning', 'Morning Routine'), ('school', 'School Time'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night Routine'), ('meals', 'Meals'), ('play', 'Play Time'), ('study', 'Study Time'), ('other', 'Other')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(default='time-outline', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Routine Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoutineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('age_group', models.CharField(choices=[('toddler', '1-3 years'), ('preschool', '4-5 years'), ('elementary', '6-10 years'), ('preteen', '11-13 years')], max_length=20)),
                ('activities_data', models.JSONField(help_text='List of activity definitions for this template')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['age_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Daily Routine', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_routines', to='api.child')),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=15)),
                ('is_recurring', models.BooleanField(default=True)),
                ('specific_days', models.JSONField(blank=True, default=list)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.IntegerField(default=5)),
                ('icon_name', models.CharField(default='time-outline', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_voice_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dailyroutine.dailyroutine')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyroutine.routinecategory')),
            ],
            options={
                'ordering': ['order', 'scheduled_time'],
                'unique_together': {('routine', 'scheduled_time', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ActivityPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_phrase', models.TextField(default="It's time for {activity}!", help_text='Spoken when activity starts. Use {activity} for activity name.')),
                ('reminder_phrase', models.TextField(default="Don't forget about {activity} in {minutes} minutes!", help_text='Use {activity} and {minutes}')),
                ('completion_phrase', models.TextField(default='Great job completing {activity}! ⭐', help_text='Spoken when marked complete')),
                ('encouragement_phrase', models.TextField(default="You're doing great! Keep it up!", help_text='Random encouragement during activity')),
                ('completion_keywords', models.JSONField(default=list, help_text="Keywords that indicate completion, e.g., ['done', 'finished', 'completed']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='dailyroutine.routineactivity')),
            ],
        ),
        migrations.CreateModel(
            name='SmartSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('time_adjustment', 'Adjust Activity Time'), ('skip_activity', 'Consider Skipping'), ('add_break', 'Add Break Time'), ('motivation', 'Needs Motivation')], max_length=50)),
                ('suggestion_text', models.TextField()),
                ('based_on_data', models.JSONField(default=dict, help_text='Pattern data that led to this suggestion')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyroutine.routineactivity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_suggestions', to='api.child')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('completion', 'Activity Completion'), ('query', 'Status Query'), ('skip', 'Skip Activity'), ('snooze', 'Snooze Reminder'), ('help', 'Help Request')], max_length=20)),
                ('spoken_text', models.TextField(help_text='What the child said')),
                ('interpreted_action', models.CharField(help_text='What system understood', max_length=200)),
                ('confidence_score', models.FloatField(default=0.0, help_text='0-1 confidence in recognition')),
                ('was_successful', models.BooleanField(default=False)),
                ('response_text', models.TextField(help_text='What assistant said back')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyroutine.routineactivity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to='api.child')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('start', 'Activity Start'), ('completion', 'Completion Confirmation'), ('encouragement', 'Encouragement'), ('warning', 'Warning/Alert')], max_length=20)),
                ('spoken_text', models.TextField()),
                ('was_spoken', models.BooleanField(default=False)),
                ('spoken_at', models.DateTimeField(blank=True, null=True)),
                ('user_responded', models.BooleanField(default=False)),
                ('response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyroutine.routineactivity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notifications', to='api.child')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type', models.CharField(choices=[('male', 'Male Voice'), ('female', 'Female Voice'), ('child', 'Child Voice'), ('robot', 'Robot Voice')], default='female', max_length=20)),
                ('language', models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('hi-IN', 'Hindi'), ('es-ES', 'Spanish')], default='en-US', max_length=10)),
                ('speech_rate', models.FloatField(default=1.0, help_text='0.5 to 2.0')),
                ('pitch', models.FloatField(default=1.0, help_text='0.5 to 2.0')),
                ('volume', models.FloatField(default=1.0, help_text='0.0 to 1.0')),
                ('speak_reminders', models.BooleanField(default=True)),
                ('speak_completions', models.BooleanField(default=True)),
                ('speak_encouragement', models.BooleanField(default=True)),
                ('enable_voice_commands', models.BooleanField(default=True)),
                ('require_wake_word', models.BooleanField(default=False)),
                ('wake_word', models.CharField(default='Hey Techy', max_length=50)),
                ('reminder_minutes_before', models.IntegerField(default=5)),
                ('reminder_sound_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_settings', to='api.child')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_via_voice', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('was_on_time', models.BooleanField(default=True)),
                ('difficulty_rating', models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='dailyroutine.routineactivity')),
                ('voice_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dailyroutine.voicecommand')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('activity', 'date')},
            },
        ),
    ]
