# Generated by Django 5.2.7 on 2026-02-21 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='weekly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_reports', to='api.child')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('screen_time', 'Screen Time'), ('learning', 'Learning'), ('creativity', 'Creativity'), ('physical', 'Physical Activity'), ('social', 'Social Skills'), ('general', 'General')], default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('icon_name', models.CharField(default='bulb-outline', help_text='Ionicons name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('based_on_data', models.JSONField(default=dict, help_text='Data that generated this recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.child')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_screen_time_minutes', models.IntegerField(default=0, help_text='Total screen time in minutes')),
                ('apps_used_count', models.IntegerField(default=0, help_text='Number of apps used')),
                ('most_used_app', models.CharField(blank=True, max_length=100, null=True)),
                ('videos_watched', models.IntegerField(default=0, help_text='Number of learning videos watched')),
                ('learning_time_minutes', models.IntegerField(default=0, help_text='Time spent on learning content')),
                ('learning_categories', models.JSONField(default=dict, help_text='Categories and time spent')),
                ('goals_achieved', models.IntegerField(default=0, help_text='Goals completed today')),
                ('goals_in_progress', models.IntegerField(default=0, help_text='Active goals')),
                ('engagement_score', models.FloatField(default=0.0, help_text='Engagement score (0-100)')),
                ('activity_change_percentage', models.FloatField(default=0.0, help_text='Change from previous day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='api.child')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['child', '-date'], name='reports_dai_child_i_145c5a_idx')],
                'unique_together': {('child', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_screen_time_hours', models.FloatField(default=0.0)),
                ('total_videos_watched', models.IntegerField(default=0)),
                ('total_goals_achieved', models.IntegerField(default=0)),
                ('avg_daily_screen_time_minutes', models.IntegerField(default=0)),
                ('avg_engagement_score', models.FloatField(default=0.0)),
                ('best_day_date', models.DateField(blank=True, null=True)),
                ('longest_learning_streak', models.IntegerField(default=0)),
                ('learning_categories_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='api.child')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('child', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('avg_daily_screen_time_minutes', models.IntegerField(default=0)),
                ('total_videos_watched', models.IntegerField(default=0)),
                ('total_goals_achieved', models.IntegerField(default=0)),
                ('screen_time_trend', models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('activity_growth_percentage', models.FloatField(default=0.0)),
                ('top_learning_category', models.CharField(blank=True, max_length=100)),
                ('most_used_app', models.CharField(blank=True, max_length=100)),
                ('engagement_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='api.child')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('child', 'week_start_date')},
            },
        ),
    ]
