# Generated by Django 5.2.7 on 2025-10-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('duration', models.FloatField(help_text='Screen time in hours')),
                ('app_used', models.CharField(blank=True, max_length=100)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_times', to='api.child')),
            ],
        ),
    ]
