# Generated by Django 5.2.7 on 2026-02-21 11:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('app_package', models.CharField(help_text='Package name like com.whatsapp', max_length=200)),
                ('daily_limit_minutes', models.IntegerField(default=60, help_text='Daily limit in minutes')),
                ('is_blocked', models.BooleanField(default=False, help_text='Completely block this app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_limits', to='api.child')),
            ],
            options={
                'unique_together': {('child', 'app_package')},
            },
        ),
        migrations.CreateModel(
            name='DailyScreenTimeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_minutes', models.IntegerField(default=0)),
                ('app_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='api.child')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('child', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('app_name', models.CharField(max_length=100)),
                ('app_package', models.CharField(max_length=200)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Screen time in minutes')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_times', to='api.child')),
            ],
            options={
                'ordering': ['-date', '-duration_minutes'],
                'unique_together': {('child', 'date', 'app_package')},
            },
        ),
    ]
