# Generated by Django 5.2.7 on 2026-02-21 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('streak', 'Learning Streak'), ('completion', 'Resource Completed'), ('quiz', 'Quiz Master'), ('explorer', 'Category Explorer'), ('helpful', 'Problem Solver'), ('consistent', 'Consistent Learner')], max_length=20)),
                ('icon_name', models.CharField(default='trophy-outline', max_length=50)),
                ('color', models.CharField(default='#f59e0b', max_length=7)),
                ('points', models.IntegerField(default=10)),
                ('requirement_value', models.IntegerField(default=1, help_text='Value needed to earn this achievement')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('language', 'Language & Reading'), ('art', 'Art & Creativity'), ('music', 'Music'), ('coding', 'Coding & Technology'), ('sports', 'Sports & Fitness'), ('social', 'Social Skills'), ('life_skills', 'Life Skills'), ('general', 'General Knowledge')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='book-outline', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Learning Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='Techy', max_length=50)),
                ('personality_type', models.CharField(choices=[('friendly', 'Friendly & Warm'), ('encouraging', 'Encouraging Coach'), ('fun', 'Fun & Playful'), ('calm', 'Calm & Patient')], default='friendly', max_length=20)),
                ('use_emojis', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('difficulty_level', models.CharField(choices=[('simple', 'Simple'), ('normal', 'Normal'), ('advanced', 'Advanced')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_personality', to='api.child')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('mood_start', models.CharField(blank=True, choices=[('happy', 'Happy 😊'), ('sad', 'Sad 😢'), ('confused', 'Confused 🤔'), ('excited', 'Excited 🎉'), ('frustrated', 'Frustrated 😤'), ('bored', 'Bored 😴'), ('neutral', 'Neutral 😐')], max_length=20)),
                ('mood_end', models.CharField(blank=True, choices=[('happy', 'Happy 😊'), ('sad', 'Sad 😢'), ('confused', 'Confused 🤔'), ('excited', 'Excited 🎉'), ('frustrated', 'Frustrated 😤'), ('bored', 'Bored 😴'), ('neutral', 'Neutral 😐')], max_length=20)),
                ('topic_category', models.CharField(blank=True, help_text='What topic was discussed', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('message_count', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='api.child')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('child', 'Child'), ('assistant', 'AI Assistant'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('suggestion', 'Learning Suggestion'), ('quiz', 'Quiz Question'), ('encouragement', 'Encouragement'), ('resource', 'Resource Link'), ('emotion', 'Emotion Check')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data like resource links, quiz answers')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learningsuggestions.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('book', 'Book'), ('activity', 'Activity'), ('game', 'Game'), ('worksheet', 'Worksheet'), ('website', 'Website'), ('podcast', 'Podcast'), ('quiz', 'Quiz')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('age_group', models.CharField(choices=[('3-5', '3-5 years'), ('6-8', '6-8 years'), ('9-11', '9-11 years'), ('12-14', '12-14 years'), ('15+', '15+ years')], max_length=10)),
                ('url', models.URLField(blank=True, help_text='Link to the resource')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(default=list, help_text='List of tags for better matching')),
                ('is_free', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learningsuggestions.learningcategory')),
            ],
            options={
                'ordering': ['category', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('homework', 'Homework Help'), ('bullying', 'Bullying'), ('friendship', 'Friendship Issue'), ('family', 'Family Problem'), ('health', 'Health Concern'), ('emotion', 'Emotional Issue'), ('learning', 'Learning Difficulty'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low - Minor issue'), ('medium', 'Medium - Needs attention'), ('high', 'High - Urgent')], default='low', max_length=10)),
                ('description', models.TextField()),
                ('ai_response', models.TextField(help_text='How chatbot responded')),
                ('parent_notified', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to='api.child')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learningsuggestions.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('explanation', models.TextField(help_text='Explanation of correct answer')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('age_group', models.CharField(default='6-8', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='learningsuggestions.learningcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ChildQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='api.child')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learningsuggestions.chatsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningsuggestions.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChildAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningsuggestions.achievement')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='api.child')),
            ],
            options={
                'unique_together': {('child', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='DailyLearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('target_minutes', models.IntegerField(default=30)),
                ('actual_minutes', models.IntegerField(default=0)),
                ('resources_target', models.IntegerField(default=2)),
                ('resources_completed', models.IntegerField(default=0)),
                ('is_achieved', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_learning_goals', to='api.child')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('child', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChildInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('notes', models.TextField(blank=True, help_text="Parent notes about child's interest")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='api.child')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningsuggestions.learningcategory')),
            ],
            options={
                'ordering': ['-interest_level'],
                'unique_together': {('child', 'category')},
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources_completed', models.IntegerField(default=0)),
                ('total_time_minutes', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningsuggestions.learningcategory')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='api.child')),
            ],
            options={
                'unique_together': {('child', 'category')},
            },
        ),
        migrations.CreateModel(
            name='LearningSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why this was suggested to this child')),
                ('relevance_score', models.FloatField(default=0.0, help_text='0-1 relevance score')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('suggested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learningsuggestions.learningcategory')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_suggestions', to='api.child')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='learningsuggestions.learningresource')),
            ],
            options={
                'ordering': ['-relevance_score', '-suggested_at'],
                'unique_together': {('child', 'resource')},
            },
        ),
    ]
