# Generated by Django 5.2.7 on 2025-10-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('education', 'Education'), ('creativity', 'Creativity'), ('devotional', 'Devotional'), ('motivational', 'Motivational')], max_length=20)),
                ('age_min', models.IntegerField(default=3)),
                ('age_max', models.IntegerField(default=17)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='api.child')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_progress', to='learningsuggestions.learningvideo')),
            ],
        ),
    ]
