# Generated by Django 5.2.7 on 2026-02-21 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('streak', 'Streak Master'), ('completion', 'Goal Crusher'), ('early', 'Early Bird'), ('consistent', 'Consistency King'), ('collaborative', 'Team Player'), ('overachiever', 'Overachiever')], max_length=20)),
                ('icon_name', models.CharField(default='medal-outline', max_length=50)),
                ('color', models.CharField(default='#f59e0b', max_length=7)),
                ('requirement', models.IntegerField(default=1, help_text='Number needed to earn')),
                ('points_reward', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('academic', 'Academic'), ('health', 'Health & Fitness'), ('hobby', 'Hobby & Skills'), ('social', 'Social & Behavior'), ('reading', 'Reading'), ('chores', 'Chores & Responsibilities'), ('screen_time', 'Screen Time'), ('creative', 'Creative'), ('personal', 'Personal Growth')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='flag-outline', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Goal Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChildPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('points_to_next_level', models.IntegerField(default=100)),
                ('current_streak', models.IntegerField(default=0, help_text='Consecutive days with completed goals')),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal_points', to='api.child')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='flag-outline', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('target_value', models.IntegerField(default=1, help_text='Target count/number')),
                ('current_value', models.IntegerField(default=0, help_text='Current progress')),
                ('unit', models.CharField(default='times', help_text='e.g., times, minutes, pages, km', max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom'), ('one_time', 'One Time')], default='daily', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('reward_points', models.IntegerField(default=10)),
                ('reward_description', models.CharField(blank=True, help_text='What they get when completed', max_length=200)),
                ('is_collaborative', models.BooleanField(default=False, help_text='Can be done with friends/family')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to other family members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.child')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='goals.goalcategory')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborativeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_contribution', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='collaborative_goals', to='api.child')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration', to='goals.goal')),
            ],
        ),
        migrations.CreateModel(
            name='GoalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], max_length=10)),
                ('author_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('is_encouragement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goals.goal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_contributed', models.IntegerField(default=0)),
                ('contribution_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.child')),
                ('collaborative_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.collaborativegoal')),
            ],
            options={
                'ordering': ['-contribution_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goals.goal')),
            ],
            options={
                'ordering': ['order', 'target_value'],
            },
        ),
        migrations.CreateModel(
            name='GoalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_text', models.TextField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='goals.goal')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='GoalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='flag-outline', max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('default_target', models.IntegerField(default=1)),
                ('default_unit', models.CharField(default='times', max_length=50)),
                ('default_frequency', models.CharField(default='daily', max_length=20)),
                ('default_priority', models.CharField(default='medium', max_length=10)),
                ('age_group', models.CharField(default='all', max_length=20)),
                ('is_popular', models.BooleanField(default=False)),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='goals.goalcategory')),
            ],
            options={
                'ordering': ['-is_popular', '-times_used'],
            },
        ),
        migrations.CreateModel(
            name='DailyGoalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('value_achieved', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='goals.goal')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('goal', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GoalAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_goals', models.IntegerField(default=0)),
                ('completed_goals', models.IntegerField(default=0)),
                ('failed_goals', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('most_active_category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_analytics', to='api.child')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('child', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='ChildGoalBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_badges', to='api.child')),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.goal')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goalbadge')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('child', 'badge')},
            },
        ),
    ]
