# Generated by Django 5.2.7 on 2025-10-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyBondingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='familybonding/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('age_group', models.CharField(choices=[('3-7', 'Age 3–7'), ('8-12', 'Age 8–12'), ('13-17', 'Age 13–17'), ('all', 'All Ages')], default='all', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='familybonding/activities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='familybonding.familybondingcategory')),
            ],
        ),
    ]
