# Generated by Django 5.2.7 on 2026-02-21 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('outdoor', 'Outdoor Activities'), ('indoor', 'Indoor Games'), ('creative', 'Creative & Arts'), ('educational', 'Educational'), ('sports', 'Sports & Fitness'), ('cooking', 'Cooking Together'), ('movie', 'Movie & Entertainment'), ('travel', 'Travel & Exploration'), ('volunteer', 'Volunteering'), ('celebration', 'Celebrations')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='people-outline', max_length=50)),
                ('color', models.CharField(default='#EC4899', max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(default='easy', max_length=15)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('age_range', models.CharField(default='All ages', max_length=50)),
                ('materials_needed', models.TextField(blank=True)),
                ('instructions', models.TextField()),
                ('is_outdoor', models.BooleanField(default=False)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('times_used', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_popular', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='familybonding.activitycategory')),
            ],
            options={
                'ordering': ['-is_popular', '-times_used'],
            },
        ),
        migrations.CreateModel(
            name='BondingStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, help_text='Consecutive weeks with activities')),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_activities', models.IntegerField(default=0)),
                ('total_hours', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonding_streak', to='api.parent')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('challenging', 'Challenging')], default='easy', max_length=15)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_outdoor', models.BooleanField(default=False)),
                ('materials_needed', models.TextField(blank=True, help_text='List of materials/items needed')),
                ('preparation_time', models.IntegerField(default=0, help_text='Preparation time in minutes')),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photo_url', models.URLField(blank=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.IntegerField(default=60)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='familybonding.activitycategory')),
                ('children', models.ManyToManyField(related_name='family_activities', to='api.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_activities', to='api.parent')),
            ],
            options={
                'verbose_name_plural': 'Family Activities',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='FamilyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_activities', models.IntegerField(default=3, help_text='Number of activities to complete')),
                ('target_hours', models.IntegerField(default=5, help_text='Total hours to spend together')),
                ('activities_completed', models.IntegerField(default=0)),
                ('hours_completed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('reward_description', models.CharField(blank=True, max_length=200)),
                ('reward_points', models.IntegerField(default=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('children', models.ManyToManyField(related_name='family_challenges', to='api.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_challenges', to='api.parent')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('memory_date', models.DateField(default=django.utils.timezone.now)),
                ('photo_urls', models.JSONField(default=list, help_text='List of photo URLs')),
                ('video_url', models.URLField(blank=True)),
                ('tags', models.JSONField(default=list, help_text="Tags like ['birthday', 'first time', 'achievement']")),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='familybonding.familyactivity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.parent')),
            ],
            options={
                'verbose_name_plural': 'Family Memories',
                'ordering': ['-memory_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('activity_count', 'Activity Count'), ('streak', 'Streak Achievement'), ('hours', 'Hours Together'), ('special', 'Special Occasion')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('value', models.IntegerField(default=0, help_text='Milestone value (100 activities, 10 week streak, etc)')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('icon_name', models.CharField(default='trophy-outline', max_length=50)),
                ('color', models.CharField(default='#F59E0B', max_length=7)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_milestones', to='api.parent')),
            ],
            options={
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], max_length=10)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='familybonding.familymemory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('favorite', models.BooleanField(default=False, help_text='Mark as favorite activity')),
                ('would_do_again', models.BooleanField(default=True)),
                ('feedback', models.TextField(blank=True)),
                ('fun_level', models.IntegerField(choices=[(1, 'Not Fun'), (2, 'Okay'), (3, 'Fun'), (4, 'Very Fun'), (5, 'Super Fun')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_ratings', to='api.child')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='familybonding.familyactivity')),
            ],
            options={
                'unique_together': {('activity', 'child')},
            },
        ),
        migrations.CreateModel(
            name='QualityTimeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_activities', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(default=0.0)),
                ('indoor_activities', models.IntegerField(default=0)),
                ('outdoor_activities', models.IntegerField(default=0)),
                ('category_breakdown', models.JSONField(default=dict, help_text='Activity count per category')),
                ('average_rating', models.FloatField(default=0.0)),
                ('average_fun_level', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_time_stats', to='api.parent')),
            ],
            options={
                'verbose_name_plural': 'Quality Time Stats',
                'ordering': ['-week_start'],
                'unique_together': {('parent', 'week_start')},
            },
        ),
    ]
