# Generated by Django 5.2.7 on 2026-02-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('warning', 'Warning'), ('alert', 'Alert'), ('info', 'Information'), ('success', 'Success'), ('limit_reached', 'Limit Reached'), ('limit_warning', 'Limit Warning'), ('app_blocked', 'App Blocked'), ('goal_achieved', 'Goal Achieved'), ('general', 'General')], default='general', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False, help_text='Does this notification require parent action?')),
                ('related_app_package', models.CharField(blank=True, help_text='Related app package if applicable', max_length=200, null=True)),
                ('related_data', models.JSONField(blank=True, help_text='Additional data for the notification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry time for notification', null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.child')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['child', '-created_at'], name='notificatio_child_i_b0b6cf_idx'), models.Index(fields=['is_read', '-created_at'], name='notificatio_is_read_1cb71a_idx')],
            },
        ),
    ]
